[tool.docstub.type_prefixes]
numbers = "numbers"
xarray = "xarray"

# Specify human-friendly aliases that can be used instead of Python-parsable
# annotations.
[tool.docstub.type_nicknames]
sequence = "Sequence"
iterable = "Iterable"
hashable = "Hashable"
iterator = "Iterator"
scalar = "numbers.Number"
dtype = "np.typing.DTypeLike"
Dataset = "xarray.Dataset"
DataTree = "xarray.DataTree"
DataArray = "xarray.DataArray"
